// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: marketplace.proto

package marketplace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketplaceMetadata struct {
	state               protoimpl.MessageState                 `protogen:"open.v1"`
	Name                string                                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DisplayName         string                                 `protobuf:"bytes,15,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Version             string                                 `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Channel             string                                 `protobuf:"bytes,3,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Owner               string                                 `protobuf:"bytes,4,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Description         string                                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Repository          string                                 `protobuf:"bytes,6,opt,name=Repository,proto3" json:"Repository,omitempty"`
	Tags                []string                               `protobuf:"bytes,7,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Category            string                                 `protobuf:"bytes,8,opt,name=Category,proto3" json:"Category,omitempty"`
	IamRoles            *MarketplaceMetadata_Iamroles          `protobuf:"bytes,9,opt,name=IamRoles,proto3" json:"IamRoles,omitempty"`
	Package             string                                 `protobuf:"bytes,10,opt,name=Package,proto3" json:"Package,omitempty"`
	ManagedDependencies *structpb.Struct                       `protobuf:"bytes,11,opt,name=ManagedDependencies,proto3" json:"ManagedDependencies,omitempty"`
	Backend             string                                 `protobuf:"bytes,12,opt,name=Backend,proto3" json:"Backend,omitempty"`
	Entrypoint          string                                 `protobuf:"bytes,13,opt,name=Entrypoint,proto3" json:"Entrypoint,omitempty"`
	WorkDirectory       string                                 `protobuf:"bytes,16,opt,name=WorkDirectory,proto3" json:"WorkDirectory,omitempty"`
	PostInstall         string                                 `protobuf:"bytes,17,opt,name=PostInstall,proto3" json:"PostInstall,omitempty"`
	PreInstall          string                                 `protobuf:"bytes,18,opt,name=PreInstall,proto3" json:"PreInstall,omitempty"`
	DefaultDeployment   *MarketplaceMetadata_Defaultdeployment `protobuf:"bytes,14,opt,name=DefaultDeployment,proto3" json:"DefaultDeployment,omitempty"`
	Dependencies        map[string]string                      `protobuf:"bytes,19,rep,name=Dependencies,proto3" json:"Dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MarketplaceMetadata) Reset() {
	*x = MarketplaceMetadata{}
	mi := &file_marketplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceMetadata) ProtoMessage() {}

func (x *MarketplaceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceMetadata.ProtoReflect.Descriptor instead.
func (*MarketplaceMetadata) Descriptor() ([]byte, []int) {
	return file_marketplace_proto_rawDescGZIP(), []int{0}
}

func (x *MarketplaceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketplaceMetadata) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MarketplaceMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MarketplaceMetadata) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *MarketplaceMetadata) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MarketplaceMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MarketplaceMetadata) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *MarketplaceMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MarketplaceMetadata) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MarketplaceMetadata) GetIamRoles() *MarketplaceMetadata_Iamroles {
	if x != nil {
		return x.IamRoles
	}
	return nil
}

func (x *MarketplaceMetadata) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *MarketplaceMetadata) GetManagedDependencies() *structpb.Struct {
	if x != nil {
		return x.ManagedDependencies
	}
	return nil
}

func (x *MarketplaceMetadata) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *MarketplaceMetadata) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *MarketplaceMetadata) GetWorkDirectory() string {
	if x != nil {
		return x.WorkDirectory
	}
	return ""
}

func (x *MarketplaceMetadata) GetPostInstall() string {
	if x != nil {
		return x.PostInstall
	}
	return ""
}

func (x *MarketplaceMetadata) GetPreInstall() string {
	if x != nil {
		return x.PreInstall
	}
	return ""
}

func (x *MarketplaceMetadata) GetDefaultDeployment() *MarketplaceMetadata_Defaultdeployment {
	if x != nil {
		return x.DefaultDeployment
	}
	return nil
}

func (x *MarketplaceMetadata) GetDependencies() map[string]string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type MarketplaceMetadata_Statement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effect        string                 `protobuf:"bytes,1,opt,name=Effect,proto3" json:"Effect,omitempty"`
	Action        []string               `protobuf:"bytes,2,rep,name=Action,proto3" json:"Action,omitempty"`
	Resource      []string               `protobuf:"bytes,3,rep,name=Resource,proto3" json:"Resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceMetadata_Statement) Reset() {
	*x = MarketplaceMetadata_Statement{}
	mi := &file_marketplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceMetadata_Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceMetadata_Statement) ProtoMessage() {}

func (x *MarketplaceMetadata_Statement) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceMetadata_Statement.ProtoReflect.Descriptor instead.
func (*MarketplaceMetadata_Statement) Descriptor() ([]byte, []int) {
	return file_marketplace_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MarketplaceMetadata_Statement) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *MarketplaceMetadata_Statement) GetAction() []string {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *MarketplaceMetadata_Statement) GetResource() []string {
	if x != nil {
		return x.Resource
	}
	return nil
}

type MarketplaceMetadata_Iamroles struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Statement     []*MarketplaceMetadata_Statement `protobuf:"bytes,1,rep,name=Statement,proto3" json:"Statement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceMetadata_Iamroles) Reset() {
	*x = MarketplaceMetadata_Iamroles{}
	mi := &file_marketplace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceMetadata_Iamroles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceMetadata_Iamroles) ProtoMessage() {}

func (x *MarketplaceMetadata_Iamroles) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceMetadata_Iamroles.ProtoReflect.Descriptor instead.
func (*MarketplaceMetadata_Iamroles) Descriptor() ([]byte, []int) {
	return file_marketplace_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MarketplaceMetadata_Iamroles) GetStatement() []*MarketplaceMetadata_Statement {
	if x != nil {
		return x.Statement
	}
	return nil
}

type MarketplaceMetadata_Variables struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Values         map[string]string      `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AdvancedValues *structpb.Struct       `protobuf:"bytes,3,opt,name=AdvancedValues,proto3" json:"AdvancedValues,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarketplaceMetadata_Variables) Reset() {
	*x = MarketplaceMetadata_Variables{}
	mi := &file_marketplace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceMetadata_Variables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceMetadata_Variables) ProtoMessage() {}

func (x *MarketplaceMetadata_Variables) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceMetadata_Variables.ProtoReflect.Descriptor instead.
func (*MarketplaceMetadata_Variables) Descriptor() ([]byte, []int) {
	return file_marketplace_proto_rawDescGZIP(), []int{0, 2}
}

func (x *MarketplaceMetadata_Variables) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *MarketplaceMetadata_Variables) GetAdvancedValues() *structpb.Struct {
	if x != nil {
		return x.AdvancedValues
	}
	return nil
}

type MarketplaceMetadata_Defaultdeployment struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Variables     *MarketplaceMetadata_Variables `protobuf:"bytes,1,opt,name=Variables,proto3" json:"Variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceMetadata_Defaultdeployment) Reset() {
	*x = MarketplaceMetadata_Defaultdeployment{}
	mi := &file_marketplace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceMetadata_Defaultdeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceMetadata_Defaultdeployment) ProtoMessage() {}

func (x *MarketplaceMetadata_Defaultdeployment) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceMetadata_Defaultdeployment.ProtoReflect.Descriptor instead.
func (*MarketplaceMetadata_Defaultdeployment) Descriptor() ([]byte, []int) {
	return file_marketplace_proto_rawDescGZIP(), []int{0, 3}
}

func (x *MarketplaceMetadata_Defaultdeployment) GetVariables() *MarketplaceMetadata_Variables {
	if x != nil {
		return x.Variables
	}
	return nil
}

var File_marketplace_proto protoreflect.FileDescriptor

const file_marketplace_proto_rawDesc = "" +
	"\n" +
	"\x11marketplace.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf0\t\n" +
	"\x13MarketplaceMetadata\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDisplayName\x18\x0f \x01(\tR\vDisplayName\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\tR\aVersion\x12\x18\n" +
	"\aChannel\x18\x03 \x01(\tR\aChannel\x12\x14\n" +
	"\x05Owner\x18\x04 \x01(\tR\x05Owner\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"Repository\x18\x06 \x01(\tR\n" +
	"Repository\x12\x12\n" +
	"\x04Tags\x18\a \x03(\tR\x04Tags\x12\x1a\n" +
	"\bCategory\x18\b \x01(\tR\bCategory\x129\n" +
	"\bIamRoles\x18\t \x01(\v2\x1d.MarketplaceMetadata.IamrolesR\bIamRoles\x12\x18\n" +
	"\aPackage\x18\n" +
	" \x01(\tR\aPackage\x12I\n" +
	"\x13ManagedDependencies\x18\v \x01(\v2\x17.google.protobuf.StructR\x13ManagedDependencies\x12\x18\n" +
	"\aBackend\x18\f \x01(\tR\aBackend\x12\x1e\n" +
	"\n" +
	"Entrypoint\x18\r \x01(\tR\n" +
	"Entrypoint\x12$\n" +
	"\rWorkDirectory\x18\x10 \x01(\tR\rWorkDirectory\x12 \n" +
	"\vPostInstall\x18\x11 \x01(\tR\vPostInstall\x12\x1e\n" +
	"\n" +
	"PreInstall\x18\x12 \x01(\tR\n" +
	"PreInstall\x12T\n" +
	"\x11DefaultDeployment\x18\x0e \x01(\v2&.MarketplaceMetadata.DefaultdeploymentR\x11DefaultDeployment\x12J\n" +
	"\fDependencies\x18\x13 \x03(\v2&.MarketplaceMetadata.DependenciesEntryR\fDependencies\x1aW\n" +
	"\tStatement\x12\x16\n" +
	"\x06Effect\x18\x01 \x01(\tR\x06Effect\x12\x16\n" +
	"\x06Action\x18\x02 \x03(\tR\x06Action\x12\x1a\n" +
	"\bResource\x18\x03 \x03(\tR\bResource\x1aH\n" +
	"\bIamroles\x12<\n" +
	"\tStatement\x18\x01 \x03(\v2\x1e.MarketplaceMetadata.StatementR\tStatement\x1a\xcb\x01\n" +
	"\tVariables\x12B\n" +
	"\x06Values\x18\x01 \x03(\v2*.MarketplaceMetadata.Variables.ValuesEntryR\x06Values\x12?\n" +
	"\x0eAdvancedValues\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0eAdvancedValues\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\x11Defaultdeployment\x12<\n" +
	"\tVariables\x18\x01 \x01(\v2\x1e.MarketplaceMetadata.VariablesR\tVariables\x1a?\n" +
	"\x11DependenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x1eZ\x1cbackend/internal/marketplaceb\x06proto3"

var (
	file_marketplace_proto_rawDescOnce sync.Once
	file_marketplace_proto_rawDescData []byte
)

func file_marketplace_proto_rawDescGZIP() []byte {
	file_marketplace_proto_rawDescOnce.Do(func() {
		file_marketplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_proto_rawDesc), len(file_marketplace_proto_rawDesc)))
	})
	return file_marketplace_proto_rawDescData
}

var file_marketplace_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_marketplace_proto_goTypes = []any{
	(*MarketplaceMetadata)(nil),                   // 0: MarketplaceMetadata
	(*MarketplaceMetadata_Statement)(nil),         // 1: MarketplaceMetadata.Statement
	(*MarketplaceMetadata_Iamroles)(nil),          // 2: MarketplaceMetadata.Iamroles
	(*MarketplaceMetadata_Variables)(nil),         // 3: MarketplaceMetadata.Variables
	(*MarketplaceMetadata_Defaultdeployment)(nil), // 4: MarketplaceMetadata.Defaultdeployment
	nil,                     // 5: MarketplaceMetadata.DependenciesEntry
	nil,                     // 6: MarketplaceMetadata.Variables.ValuesEntry
	(*structpb.Struct)(nil), // 7: google.protobuf.Struct
}
var file_marketplace_proto_depIdxs = []int32{
	2, // 0: MarketplaceMetadata.IamRoles:type_name -> MarketplaceMetadata.Iamroles
	7, // 1: MarketplaceMetadata.ManagedDependencies:type_name -> google.protobuf.Struct
	4, // 2: MarketplaceMetadata.DefaultDeployment:type_name -> MarketplaceMetadata.Defaultdeployment
	5, // 3: MarketplaceMetadata.Dependencies:type_name -> MarketplaceMetadata.DependenciesEntry
	1, // 4: MarketplaceMetadata.Iamroles.Statement:type_name -> MarketplaceMetadata.Statement
	6, // 5: MarketplaceMetadata.Variables.Values:type_name -> MarketplaceMetadata.Variables.ValuesEntry
	7, // 6: MarketplaceMetadata.Variables.AdvancedValues:type_name -> google.protobuf.Struct
	3, // 7: MarketplaceMetadata.Defaultdeployment.Variables:type_name -> MarketplaceMetadata.Variables
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_marketplace_proto_init() }
func file_marketplace_proto_init() {
	if File_marketplace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_proto_rawDesc), len(file_marketplace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_proto_goTypes,
		DependencyIndexes: file_marketplace_proto_depIdxs,
		MessageInfos:      file_marketplace_proto_msgTypes,
	}.Build()
	File_marketplace_proto = out.File
	file_marketplace_proto_goTypes = nil
	file_marketplace_proto_depIdxs = nil
}
